###########
# site.title, site.url, site.author.name

title:   'Site Pre-set'
author: 
  name:  'My name'
description:  A generic, simple site by alex-esc, forked from henrythemes' jekyll-minimal-theme.

## note: 
#  use site.path in your templates to make it work for both protocols e.g. http and https
#  use site.url only inside the web feed template (e.g. requires full url incl. protocol)
path: '/post-clone'
url:  'https://alex-esc.github.io'
baseurl: '/post-clone'

## Menu buttons


other:
  about: 'https://alex-esc.github.io/en_us/pages/about.html'
  comments: 'https://www.reddit.com/r/alex_esc_reddit/'
  emaillist: https://feedburner.google.com/fb/a/mailverify?uri=alex-esc&amp;loc=en_US
  activitypubfeed: https://bots.tinysubversions.com/u/alex_esc_blog_posts
  twitterfeed: https://twitter.com/alex_esc_tweets
  mediumfeed: https://medium.com/@alexesc

########
# more settings

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded

permalink: /:title.html

exclude:
- README.md


safe: true
lsi: false

plugins:
  - jekyll-redirect-from

excerpt_separator: <!--more-->

kramdown:
  auto_ids: true # Auto-generate ID's for headings